# ==============================================================================
# CELESTIALSKY SHADERPACK - BLOCK PROPERTIES MAPPING (OptiFine / Iris)
# ==============================================================================

# Fire & Campfire Blocks (Normal Orange Fire)
block.10001=minecraft:fire minecraft:campfire

# Soul Fire & Soul Campfire Blocks (Blue Cyan Ionized Plasma)
block.10002=minecraft:soul_fire minecraft:soul_campfire
